using BinanceSDK.Helpers.Request;

namespace BinanceSDK.DTO.V3.Trade
{
	public class CancelOrderRequest : Req
	{
		[Query("symbol")]
		public readonly string Symbol;

		[Query("orderId")]
		public long? OrderID;

		[Query("origClientOrderId")]
		public string? OrigClientOrderID;

		/// <summary>
		/// Used to uniquely identify this cancel.Automatically generated by default.
		/// </summary>
		[Query("newClientOrderId")]
		public string? NewClientOrderId;


		public CancelOrderRequest(string symbol) {
			Symbol = symbol;
		}
	}
}
